### PR TITLE
Removed double import and upgraded dependencies

### PR DESCRIPTION
**Pull request by Fenopiu**
Removed useless double import of App.css in App.tsx. Upgraded quite all packages and now it compile.

### CODE REVIEW

**Comment by karlvr** [comment]
@Fenopiu thank you very much for this. I would like to have the repo without semicolons, which is set in the `tslint.json`. Would you be able to remove the semicolons from your changes? Also I have setup the `baseUrl` in `tsconfig.json` so that imports can work like `import { RootStoreState } from 'root/index'` rather than `import { RootStoreState } from '../root/index'`, so I'd like to leave those as they are too. Everything is fantastic! If you're happy, please update and I'll re-review. Thanks again.

**Comment by karlvr** [comment]
We also need to update the README with the steps to create the repo!

**Comment by Fenopiu** [comment]
I don't use Yarn, so I don't know the step to be done.
The NPM the installation doesn't change, "npm i" install everything you need.
Instead to upgrade you have to:

- uninstall react-scripts-ts --> npm uninstall react-scripts-ts
- install create-react-app --> npm i react-scripts@latest
- install new dependencies --> npm i 

ASAP I will bring back baseUrl on (was burned on the upgrade process) and remove the semicolons... even if it is a stab for me! ;-P

P.S.
I've done the same PR to your https://github.com/karlvr/react-redux-typescript-swagger-api-pattern, I don't know if you noticed that.

**Comment by Fenopiu** [comment]
Ok, I've pushed the mods.
With new TSconfig rules, baseUrl can be only "src" or "node-modules" so I've chosen "src" that is half of your request.
I've removed the semicolons.
I've updated the TSlint to the new rules format (especially for member-ordering".
I've updated the readme file with npm upgrade instructions... for Yarn, you have to do it by yourself 'cause I've never used it.

**Comment by karlvr** [comment]
@Fenopiu thank you very much for this. It so happens that I'm starting a new project so this was very relevant. I have actually run through the process of recreating the project from scratch and converting to eslint, as TSLint is going to be deprecated soon, and I think recreating from scratch has stripped away a few more things that aren't required in the original setup (including yarn).

**Comment by karlvr** [comment]
@Fenopiu I'll close this PR as I believe I've addressed it with that push. Thanks again for this PR, and my apologies that I didn't get to merge it with this redo.

**Pull request closed without merging**
